name: budget_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2

  #BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  notifier_bloc:
    git: https://github.com/s-deer/notifier_bloc.git

  #DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  #Routing
  auto_route: ^7.8.0

  #Localization/Internalization
  slang: ^3.22.0
  slang_flutter: ^3.22.0
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.1

  #Error handling
  dartz: ^0.10.1

  #Local DB
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.0

  #Utils
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4

  build_runner: ^2.4.6
  drift_dev: ^2.10.0
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.3.0
  slang_build_runner: ^3.22.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
